export const countries = [
  { code: "aw", label: "Aruba", flag: "/images/flags/aw.svg", currency: "$" },
  { code: "af", label: "Afghanistan", flag: "/images/flags/af.svg", currency: "$" },
  { code: "ao", label: "Angola", flag: "/images/flags/ao.svg", currency: "$" },
  { code: "ai", label: "Anguilla", flag: "/images/flags/ai.svg", currency: "$" },
  { code: "ax", label: "Åland Islands", flag: "/images/flags/ax.svg", currency: "$" },
  { code: "al", label: "Albania", flag: "/images/flags/al.svg", currency: "$" },
  { code: "ad", label: "Andorra", flag: "/images/flags/ad.svg", currency: "$" },
  { code: "ae", label: "United Arab Emirates", flag: "/images/flags/ae.svg", currency: "UAD" },
  { code: "ar", label: "Argentina", flag: "/images/flags/ar.svg", currency: "$" },
  { code: "am", label: "Armenia", flag: "/images/flags/am.svg", currency: "$" },
  { code: "as", label: "American Samoa", flag: "/images/flags/as.svg", currency: "$" },
  { code: "aq", label: "Antarctica", flag: "/images/flags/aq.svg", currency: "$" },
  { code: "tf", label: "French Southern Territories", flag: "/images/flags/tf.svg", currency: "$" },
  { code: "ag", label: "Antigua and Barbuda", flag: "/images/flags/ag.svg", currency: "$" },
  { code: "au", label: "Australia", flag: "/images/flags/au.svg", currency: "$" },
  { code: "at", label: "Austria", flag: "/images/flags/at.svg", currency: "$" },
  { code: "az", label: "Azerbaijan", flag: "/images/flags/az.svg", currency: "$" },
  { code: "bi", label: "Burundi", flag: "/images/flags/bi.svg", currency: "$" },
  { code: "be", label: "Belgium", flag: "/images/flags/be.svg", currency: "$" },
  { code: "bj", label: "Benin", flag: "/images/flags/bj.svg", currency: "$" },
  { code: "bq", label: "Bonaire, Sint Eustatius and Saba", flag: "/images/flags/bq.svg", currency: "$" },
  { code: "bf", label: "Burkina Faso", flag: "/images/flags/bf.svg", currency: "$" },
  { code: "bd", label: "Bangladesh", flag: "/images/flags/bd.svg", currency: "$" },
  { code: "bg", label: "Bulgaria", flag: "/images/flags/bg.svg", currency: "$" },
  { code: "bh", label: "Bahrain", flag: "/images/flags/bh.svg", currency: "$" },
  { code: "bs", label: "Bahamas", flag: "/images/flags/bs.svg", currency: "$" },
  { code: "ba", label: "Bosnia and Herzegovina", flag: "/images/flags/ba.svg", currency: "$" },
  { code: "bl", label: "Saint Barthélemy", flag: "/images/flags/bl.svg", currency: "$" },
  { code: "by", label: "Belarus", flag: "/images/flags/by.svg", currency: "$" },
  { code: "bz", label: "Belize", flag: "/images/flags/bz.svg", currency: "$" },
  { code: "bm", label: "Bermuda", flag: "/images/flags/bm.svg", currency: "$" },
  { code: "bo", label: "Bolivia, Plurinational State of", flag: "/images/flags/bo.svg", currency: "$" },
  { code: "br", label: "Brazil", flag: "/images/flags/br.svg", currency: "$" },
  { code: "bb", label: "Barbados", flag: "/images/flags/bb.svg", currency: "$" },
  { code: "bn", label: "Brunei Darussalam", flag: "/images/flags/bn.svg", currency: "$" },
  { code: "bt", label: "Bhutan", flag: "/images/flags/bt.svg", currency: "$" },
  { code: "bv", label: "Bouvet Island", flag: "/images/flags/bv.svg", currency: "$" },
  { code: "bw", label: "Botswana", flag: "/images/flags/bw.svg", currency: "$" },
  { code: "cf", label: "Central African Republic", flag: "/images/flags/cf.svg", currency: "$" },
  { code: "ca", label: "Canada", flag: "/images/flags/ca.svg", currency: "$" },
  { code: "cc", label: "Cocos (Keeling) Islands", flag: "/images/flags/cc.svg", currency: "$" },
  { code: "ch", label: "Switzerland", flag: "/images/flags/ch.svg", currency: "$" },
  { code: "cl", label: "Chile", flag: "/images/flags/cl.svg", currency: "$" },
  { code: "cn", label: "China", flag: "/images/flags/cn.svg", currency: "$" },
  { code: "ci", label: "Côte d'Ivoire", flag: "/images/flags/ci.svg", currency: "$" },
  { code: "cm", label: "Cameroon", flag: "/images/flags/cm.svg", currency: "$" },
  { code: "cd", label: "Congo, The Democratic Republic of the", flag: "/images/flags/cd.svg", currency: "$" },
  { code: "cg", label: "Congo", flag: "/images/flags/cg.svg", currency: "$" },
  { code: "ck", label: "Cook Islands", flag: "/images/flags/ck.svg", currency: "$" },
  { code: "co", label: "Colombia", flag: "/images/flags/co.svg", currency: "$" },
  { code: "km", label: "Comoros", flag: "/images/flags/km.svg", currency: "$" },
  { code: "cv", label: "Cabo Verde", flag: "/images/flags/cv.svg", currency: "$" },
  { code: "cr", label: "Costa Rica", flag: "/images/flags/cr.svg", currency: "$" },
  { code: "cu", label: "Cuba", flag: "/images/flags/cu.svg", currency: "$" },
  { code: "cw", label: "Curaçao", flag: "/images/flags/cw.svg", currency: "$" },
  { code: "cx", label: "Christmas Island", flag: "/images/flags/cx.svg", currency: "$" },
  { code: "ky", label: "Cayman Islands", flag: "/images/flags/ky.svg", currency: "$" },
  { code: "cy", label: "Cyprus", flag: "/images/flags/cy.svg", currency: "$" },
  { code: "cz", label: "Czechia", flag: "/images/flags/cz.svg", currency: "$" },
  { code: "de", label: "Germany", flag: "/images/flags/de.svg", currency: "$" },
  { code: "dj", label: "Djibouti", flag: "/images/flags/dj.svg", currency: "$" },
  { code: "dm", label: "Dominica", flag: "/images/flags/dm.svg", currency: "$" },
  { code: "dk", label: "Denmark", flag: "/images/flags/dk.svg", currency: "$" },
  { code: "do", label: "Dominican Republic", flag: "/images/flags/do.svg", currency: "$" },
  { code: "dz", label: "Algeria", flag: "/images/flags/dz.svg", currency: "$" },
  { code: "ec", label: "Ecuador", flag: "/images/flags/ec.svg", currency: "$" },
  { code: "eg", label: "Egypt", flag: "/images/flags/eg.svg", currency: "$" },
  { code: "er", label: "Eritrea", flag: "/images/flags/er.svg", currency: "$" },
  { code: "eh", label: "Western Sahara", flag: "/images/flags/eh.svg", currency: "$" },
  { code: "es", label: "Spain", flag: "/images/flags/es.svg", currency: "$" },
  { code: "ee", label: "Estonia", flag: "/images/flags/ee.svg", currency: "$" },
  { code: "et", label: "Ethiopia", flag: "/images/flags/et.svg", currency: "$" },
  { code: "fi", label: "Finland", flag: "/images/flags/fi.svg", currency: "$" },
  { code: "fj", label: "Fiji", flag: "/images/flags/fj.svg", currency: "$" },
  { code: "fk", label: "Falkland Islands (Malvinas)", flag: "/images/flags/fk.svg", currency: "$" },
  { code: "fr", label: "France", flag: "/images/flags/fr.svg", currency: "$" },
  { code: "fo", label: "Faroe Islands", flag: "/images/flags/fo.svg", currency: "$" },
  { code: "fm", label: "Micronesia, Federated States of", flag: "/images/flags/fm.svg", currency: "$" },
  { code: "ga", label: "Gabon", flag: "/images/flags/ga.svg", currency: "$" },
  { code: "gb", label: "United Kingdom", flag: "/images/flags/gb.svg", currency: "$" },
  { code: "ge", label: "Georgia", flag: "/images/flags/ge.svg", currency: "$" },
  { code: "gg", label: "Guernsey", flag: "/images/flags/gg.svg", currency: "$" },
  { code: "gh", label: "Ghana", flag: "/images/flags/gh.svg", currency: "$" },
  { code: "gi", label: "Gibraltar", flag: "/images/flags/gi.svg", currency: "$" },
  { code: "gn", label: "Guinea", flag: "/images/flags/gn.svg", currency: "$" },
  { code: "gp", label: "Guadeloupe", flag: "/images/flags/gp.svg", currency: "$" },
  { code: "gm", label: "Gambia", flag: "/images/flags/gm.svg", currency: "$" },
  { code: "gw", label: "Guinea-Bissau", flag: "/images/flags/gw.svg", currency: "$" },
  { code: "gq", label: "Equatorial Guinea", flag: "/images/flags/gq.svg", currency: "$" },
  { code: "gr", label: "Greece", flag: "/images/flags/gr.svg", currency: "$" },
  { code: "gd", label: "Grenada", flag: "/images/flags/gd.svg", currency: "$" },
  { code: "gl", label: "Greenland", flag: "/images/flags/gl.svg", currency: "$" },
  { code: "gt", label: "Guatemala", flag: "/images/flags/gt.svg", currency: "$" },
  { code: "gf", label: "French Guiana", flag: "/images/flags/gf.svg", currency: "$" },
  { code: "gu", label: "Guam", flag: "/images/flags/gu.svg", currency: "$" },
  { code: "gy", label: "Guyana", flag: "/images/flags/gy.svg", currency: "$" },
  { code: "hk", label: "Hong Kong", flag: "/images/flags/hk.svg", currency: "$" },
  { code: "hm", label: "Heard Island and McDonald Islands", flag: "/images/flags/hm.svg", currency: "$" },
  { code: "hn", label: "Honduras", flag: "/images/flags/hn.svg", currency: "$" },
  { code: "hr", label: "Croatia", flag: "/images/flags/hr.svg", currency: "$" },
  { code: "ht", label: "Haiti", flag: "/images/flags/ht.svg", currency: "$" },
  { code: "hu", label: "Hungary", flag: "/images/flags/hu.svg", currency: "$" },
  { code: "id", label: "Indonesia", flag: "/images/flags/id.svg", currency: "$" },
  { code: "im", label: "Isle of Man", flag: "/images/flags/im.svg", currency: "$" },
  { code: "in", label: "India", flag: "/images/flags/in.svg", currency: "$" },
  { code: "io", label: "British Indian Ocean Territory", flag: "/images/flags/io.svg", currency: "$" },
  { code: "ie", label: "Ireland", flag: "/images/flags/ie.svg", currency: "$" },
  { code: "ir", label: "Iran, Islamic Republic of", flag: "/images/flags/ir.svg", currency: "ريال" },
  { code: "iq", label: "Iraq", flag: "/images/flags/iq.svg", currency: "$" },
  { code: "is", label: "Iceland", flag: "/images/flags/is.svg", currency: "$" },
  { code: "il", label: "Israel", flag: "/images/flags/il.svg", currency: "$" },
  { code: "it", label: "Italy", flag: "/images/flags/it.svg", currency: "$" },
  { code: "jm", label: "Jamaica", flag: "/images/flags/jm.svg", currency: "$" },
  { code: "je", label: "Jersey", flag: "/images/flags/je.svg", currency: "$" },
  { code: "jo", label: "Jordan", flag: "/images/flags/jo.svg", currency: "$" },
  { code: "jp", label: "Japan", flag: "/images/flags/jp.svg", currency: "$" },
  { code: "kz", label: "Kazakhstan", flag: "/images/flags/kz.svg", currency: "$" },
  { code: "ke", label: "Kenya", flag: "/images/flags/ke.svg", currency: "$" },
  { code: "kg", label: "Kyrgyzstan", flag: "/images/flags/kg.svg", currency: "$" },
  { code: "kh", label: "Cambodia", flag: "/images/flags/kh.svg", currency: "$" },
  { code: "ki", label: "Kiribati", flag: "/images/flags/ki.svg", currency: "$" },
  { code: "kn", label: "Saint Kitts and Nevis", flag: "/images/flags/kn.svg", currency: "$" },
  { code: "kr", label: "Korea, Republic of", flag: "/images/flags/kr.svg", currency: "$" },
  { code: "kw", label: "Kuwait", flag: "/images/flags/kw.svg", currency: "$" },
  { code: "la", label: "Lao People's Democratic Republic", flag: "/images/flags/la.svg", currency: "$" },
  { code: "lb", label: "Lebanon", flag: "/images/flags/lb.svg", currency: "$" },
  { code: "lr", label: "Liberia", flag: "/images/flags/lr.svg", currency: "$" },
  { code: "ly", label: "Libya", flag: "/images/flags/ly.svg", currency: "$" },
  { code: "lc", label: "Saint Lucia", flag: "/images/flags/lc.svg", currency: "$" },
  { code: "li", label: "Liechtenstein", flag: "/images/flags/li.svg", currency: "$" },
  { code: "lk", label: "Sri Lanka", flag: "/images/flags/lk.svg", currency: "$" },
  { code: "ls", label: "Lesotho", flag: "/images/flags/ls.svg", currency: "$" },
  { code: "lt", label: "Lithuania", flag: "/images/flags/lt.svg", currency: "$" },
  { code: "lu", label: "Luxembourg", flag: "/images/flags/lu.svg", currency: "$" },
  { code: "lv", label: "Latvia", flag: "/images/flags/lv.svg", currency: "$" },
  { code: "mo", label: "Macao", flag: "/images/flags/mo.svg", currency: "$" },
  { code: "mf", label: "Saint Martin (French part)", flag: "/images/flags/mf.svg", currency: "$" },
  { code: "ma", label: "Morocco", flag: "/images/flags/ma.svg", currency: "$" },
  { code: "mc", label: "Monaco", flag: "/images/flags/mc.svg", currency: "$" },
  { code: "md", label: "Moldova, Republic of", flag: "/images/flags/md.svg", currency: "$" },
  { code: "mg", label: "Madagascar", flag: "/images/flags/mg.svg", currency: "$" },
  { code: "mv", label: "Maldives", flag: "/images/flags/mv.svg", currency: "$" },
  { code: "mx", label: "Mexico", flag: "/images/flags/mx.svg", currency: "$" },
  { code: "mh", label: "Marshall Islands", flag: "/images/flags/mh.svg", currency: "$" },
  { code: "mk", label: "North Macedonia", flag: "/images/flags/mk.svg", currency: "$" },
  { code: "ml", label: "Mali", flag: "/images/flags/ml.svg", currency: "$" },
  { code: "mt", label: "Malta", flag: "/images/flags/mt.svg", currency: "$" },
  { code: "mm", label: "Myanmar", flag: "/images/flags/mm.svg", currency: "$" },
  { code: "me", label: "Montenegro", flag: "/images/flags/me.svg", currency: "$" },
  { code: "mn", label: "Mongolia", flag: "/images/flags/mn.svg", currency: "$" },
  { code: "mp", label: "Northern Mariana Islands", flag: "/images/flags/mp.svg", currency: "$" },
  { code: "mz", label: "Mozambique", flag: "/images/flags/mz.svg", currency: "$" },
  { code: "mr", label: "Mauritania", flag: "/images/flags/mr.svg", currency: "$" },
  { code: "ms", label: "Montserrat", flag: "/images/flags/ms.svg", currency: "$" },
  { code: "mq", label: "Martinique", flag: "/images/flags/mq.svg", currency: "$" },
  { code: "mu", label: "Mauritius", flag: "/images/flags/mu.svg", currency: "$" },
  { code: "mw", label: "Malawi", flag: "/images/flags/mw.svg", currency: "$" },
  { code: "my", label: "Malaysia", flag: "/images/flags/my.svg", currency: "$" },
  { code: "yt", label: "Mayotte", flag: "/images/flags/yt.svg", currency: "$" },
  { code: "na", label: "Namibia", flag: "/images/flags/na.svg", currency: "$" },
  { code: "nc", label: "New Caledonia", flag: "/images/flags/nc.svg", currency: "$" },
  { code: "ne", label: "Niger", flag: "/images/flags/ne.svg", currency: "$" },
  { code: "nf", label: "Norfolk Island", flag: "/images/flags/nf.svg", currency: "$" },
  { code: "ng", label: "Nigeria", flag: "/images/flags/ng.svg", currency: "$" },
  { code: "ni", label: "Nicaragua", flag: "/images/flags/ni.svg", currency: "$" },
  { code: "nu", label: "Niue", flag: "/images/flags/nu.svg", currency: "$" },
  { code: "nl", label: "Netherlands", flag: "/images/flags/nl.svg", currency: "$" },
  { code: "no", label: "Norway", flag: "/images/flags/no.svg", currency: "$" },
  { code: "np", label: "Nepal", flag: "/images/flags/np.svg", currency: "$" },
  { code: "nr", label: "Nauru", flag: "/images/flags/nr.svg", currency: "$" },
  { code: "nz", label: "New Zealand", flag: "/images/flags/nz.svg", currency: "$" },
  { code: "om", label: "Oman", flag: "/images/flags/om.svg", currency: "$" },
  { code: "pk", label: "Pakistan", flag: "/images/flags/pk.svg", currency: "$" },
  { code: "pa", label: "Panama", flag: "/images/flags/pa.svg", currency: "$" },
  { code: "pn", label: "Pitcairn", flag: "/images/flags/pn.svg", currency: "$" },
  { code: "pe", label: "Peru", flag: "/images/flags/pe.svg", currency: "$" },
  { code: "ph", label: "Philippines", flag: "/images/flags/ph.svg", currency: "$" },
  { code: "pw", label: "Palau", flag: "/images/flags/pw.svg", currency: "$" },
  { code: "pg", label: "Papua New Guinea", flag: "/images/flags/pg.svg", currency: "$" },
  { code: "pl", label: "Poland", flag: "/images/flags/pl.svg", currency: "$" },
  { code: "pr", label: "Puerto Rico", flag: "/images/flags/pr.svg", currency: "$" },
  { code: "kp", label: "Korea, Democratic People's Republic of", flag: "/images/flags/kp.svg", currency: "$" },
  { code: "pt", label: "Portugal", flag: "/images/flags/pt.svg", currency: "€" },
  { code: "py", label: "Paraguay", flag: "/images/flags/py.svg", currency: "$" },
  { code: "ps", label: "Palestine, State of", flag: "/images/flags/ps.svg", currency: "$" },
  { code: "pf", label: "French Polynesia", flag: "/images/flags/pf.svg", currency: "$" },
  { code: "qa", label: "Qatar", flag: "/images/flags/qa.svg", currency: "$" },
  { code: "re", label: "Réunion", flag: "/images/flags/re.svg", currency: "$" },
  { code: "ro", label: "Romania", flag: "/images/flags/ro.svg", currency: "$" },
  { code: "ru", label: "Russian Federation", flag: "/images/flags/ru.svg", currency: "$" },
  { code: "rw", label: "Rwanda", flag: "/images/flags/rw.svg", currency: "$" },
  { code: "sa", label: "Saudi Arabia", flag: "/images/flags/sa.svg", currency: "$" },
  { code: "sd", label: "Sudan", flag: "/images/flags/sd.svg", currency: "$" },
  { code: "sn", label: "Senegal", flag: "/images/flags/sn.svg", currency: "$" },
  { code: "sg", label: "Singapore", flag: "/images/flags/sg.svg", currency: "$" },
  { code: "gs", label: "South Georgia and the South Sandwich Islands", flag: "/images/flags/gs.svg", currency: "$" },
  { code: "sh", label: "Saint Helena, Ascension and Tristan da Cunha", flag: "/images/flags/sh.svg", currency: "$" },
  { code: "sj", label: "Svalbard and Jan Mayen", flag: "/images/flags/sj.svg", currency: "$" },
  { code: "sb", label: "Solomon Islands", flag: "/images/flags/sb.svg", currency: "$" },
  { code: "sl", label: "Sierra Leone", flag: "/images/flags/sl.svg", currency: "$" },
  { code: "sv", label: "El Salvador", flag: "/images/flags/sv.svg", currency: "$" },
  { code: "sm", label: "San Marino", flag: "/images/flags/sm.svg", currency: "$" },
  { code: "so", label: "Somalia", flag: "/images/flags/so.svg", currency: "$" },
  { code: "pm", label: "Saint Pierre and Miquelon", flag: "/images/flags/pm.svg", currency: "$" },
  { code: "rs", label: "Serbia", flag: "/images/flags/rs.svg", currency: "$" },
  { code: "ss", label: "South Sudan", flag: "/images/flags/ss.svg", currency: "$" },
  { code: "st", label: "Sao Tome and Principe", flag: "/images/flags/st.svg", currency: "$" },
  { code: "sr", label: "Suriname", flag: "/images/flags/sr.svg", currency: "$" },
  { code: "sk", label: "Slovakia", flag: "/images/flags/sk.svg", currency: "$" },
  { code: "si", label: "Slovenia", flag: "/images/flags/si.svg", currency: "$" },
  { code: "se", label: "Sweden", flag: "/images/flags/se.svg", currency: "$" },
  { code: "sz", label: "Eswatini", flag: "/images/flags/sz.svg", currency: "$" },
  { code: "sx", label: "Sint Maarten (Dutch part)", flag: "/images/flags/sx.svg", currency: "$" },
  { code: "sc", label: "Seychelles", flag: "/images/flags/sc.svg", currency: "$" },
  { code: "sy", label: "Syrian Arab Republic", flag: "/images/flags/sy.svg", currency: "$" },
  { code: "tc", label: "Turks and Caicos Islands", flag: "/images/flags/tc.svg", currency: "$" },
  { code: "td", label: "Chad", flag: "/images/flags/td.svg", currency: "$" },
  { code: "tg", label: "Togo", flag: "/images/flags/tg.svg", currency: "$" },
  { code: "th", label: "Thailand", flag: "/images/flags/th.svg", currency: "$" },
  { code: "tj", label: "Tajikistan", flag: "/images/flags/tj.svg", currency: "$" },
  { code: "tk", label: "Tokelau", flag: "/images/flags/tk.svg", currency: "$" },
  { code: "tm", label: "Turkmenistan", flag: "/images/flags/tm.svg", currency: "$" },
  { code: "tl", label: "Timor-Leste", flag: "/images/flags/tl.svg", currency: "$" },
  { code: "to", label: "Tonga", flag: "/images/flags/to.svg", currency: "$" },
  { code: "tt", label: "Trinidad and Tobago", flag: "/images/flags/tt.svg", currency: "$" },
  { code: "tn", label: "Tunisia", flag: "/images/flags/tn.svg", currency: "$" },
  { code: "tr", label: "Turkey", flag: "/images/flags/tr.svg", currency: "$" },
  { code: "tv", label: "Tuvalu", flag: "/images/flags/tv.svg", currency: "$" },
  { code: "tw", label: "Taiwan, Province of China", flag: "/images/flags/tw.svg", currency: "$" },
  { code: "tz", label: "Tanzania, United Republic of", flag: "/images/flags/tz.svg", currency: "$" },
  { code: "ug", label: "Uganda", flag: "/images/flags/ug.svg", currency: "$" },
  { code: "ua", label: "Ukraine", flag: "/images/flags/ua.svg", currency: "$" },
  { code: "um", label: "United States Minor Outlying Islands", flag: "/images/flags/um.svg", currency: "$" },
  { code: "uy", label: "Uruguay", flag: "/images/flags/uy.svg", currency: "$" },
  { code: "us", label: "United States", flag: "/images/flags/us.svg", currency: "$" },
  { code: "uz", label: "Uzbekistan", flag: "/images/flags/uz.svg", currency: "$" },
  { code: "va", label: "Holy See (Vatican City State)", flag: "/images/flags/va.svg", currency: "$" },
  { code: "vc", label: "Saint Vincent and the Grenadines", flag: "/images/flags/vc.svg", currency: "$" },
  { code: "ve", label: "Venezuela, Bolivarian Republic of", flag: "/images/flags/ve.svg", currency: "$" },
  { code: "vg", label: "Virgin Islands, British", flag: "/images/flags/vg.svg", currency: "$" },
  { code: "vi", label: "Virgin Islands, U.S.", flag: "/images/flags/vi.svg", currency: "$" },
  { code: "vn", label: "Viet Nam", flag: "/images/flags/vn.svg", currency: "$" },
  { code: "vu", label: "Vanuatu", flag: "/images/flags/vu.svg", currency: "$" },
  { code: "wf", label: "Wallis and Futuna", flag: "/images/flags/wf.svg", currency: "$" },
  { code: "ws", label: "Samoa", flag: "/images/flags/ws.svg", currency: "$" },
  { code: "ye", label: "Yemen", flag: "/images/flags/ye.svg", currency: "$" },
  { code: "za", label: "South Africa", flag: "/images/flags/za.svg", currency: "$" },
  { code: "zm", label: "Zambia", flag: "/images/flags/zm.svg", currency: "$" },
  { code: "zw", label: "Zimbabwe", flag: "/images/flags/zw.svg", currency: "$" },
];
