export const USERS_MOCK_DATA = [
  {
    id: "jsdhgf8743dshfh874",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "+1234567890",
    email: "john.doe@example.com",
    shebaNumber: "IR820540102680020817909002",
    password: "hashed_password_1",
    birthdate: "1990-01-01",
    cart: [],
    wishlist: [],
    addresses: [],
    createdAt: "2023-01-01",
    updatedAt: "2023-01-02",
  },
  {
    id: "asdhg2345sdgdfg234",
    firstName: "Jane",
    lastName: "Smith",
    phoneNumber: "+1987654321",
    email: "jane.smith@example.com",
    shebaNumber: "IR820540102680020817909003",
    password: "hashed_password_2",
    birthdate: "1985-05-15",
    cart: [],
    wishlist: [],
    addresses: [],
    createdAt: "2023-02-01",
    updatedAt: "2023-02-02",
  },
  {
    id: "qwe2345rty6789uio12",
    firstName: "Alice",
    lastName: "Johnson",
    phoneNumber: "+1122334455",
    email: "alice.johnson@example.com",
    shebaNumber: "IR820540102680020817909004",
    password: "hashed_password_3",
    birthdate: "1992-07-21",
    cart: [],
    wishlist: [],
    addresses: [],
    createdAt: "2023-03-01",
    updatedAt: "2023-03-02",
  },
  {
    id: "zxcvbnm0987654321",
    firstName: "Bob",
    lastName: "Williams",
    phoneNumber: "+1222333444",
    email: "bob.williams@example.com",
    shebaNumber: "IR820540102680020817909005",
    password: "hashed_password_4",
    birthdate: "1988-11-30",
    cart: [],
    wishlist: [],
    addresses: [],
    createdAt: "2023-04-01",
    updatedAt: "2023-04-02",
  },
  {
    id: "poiuytrewq123456789",
    firstName: "Charlie",
    lastName: "Brown",
    phoneNumber: "+1444555666",
    email: "charlie.brown@example.com",
    shebaNumber: "IR820540102680020817909006",
    password: "hashed_password_5",
    birthdate: "1995-03-10",
    cart: [],
    wishlist: [],
    addresses: [],
    createdAt: "2023-05-01",
    updatedAt: "2023-05-02",
  },
  {
    id: "lkjhgfdsa987654321",
    firstName: "Diana",
    lastName: "Evans",
    phoneNumber: "+1555666777",
    email: "diana.evans@example.com",
    shebaNumber: "IR820540102680020817909007",
    password: "hashed_password_6",
    birthdate: "1993-09-25",
    cart: [],
    wishlist: [],
    addresses: [],
    createdAt: "2023-06-01",
    updatedAt: "2023-06-02",
  },
  {
    id: "mnbvcxz1234567890",
    firstName: "Ethan",
    lastName: "Clark",
    phoneNumber: "+1666777888",
    email: "ethan.clark@example.com",
    shebaNumber: "IR820540102680020817909008",
    password: "hashed_password_7",
    birthdate: "1991-12-12",
    cart: [],
    wishlist: [],
    addresses: [],
    createdAt: "2023-07-01",
    updatedAt: "2023-07-02",
  },
];

export const ADMINS_MOCK_DATA = [
  {
    id: "admin1234567890",
    firstName: "Admin",
    lastName: "User",
    username: "admin.user",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-01-01",
    updatedAt: "2023-01-02",
  },
  {
    id: "admin9876543210",
    firstName: "Sarah",
    lastName: "Johnson",
    username: "sarah.johnson",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-02-01",
    updatedAt: "2023-02-05",
  },
  {
    id: "admin2468013579",
    firstName: "Michael",
    lastName: "Smith",
    username: "michael.smith",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-03-01",
    updatedAt: "2023-03-03",
  },
  {
    id: "admin1357924680",
    firstName: "Emily",
    lastName: "Davis",
    username: "emily.davis",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-03-15",
    updatedAt: "2023-03-16",
  },
  {
    id: "admin1122334455",
    firstName: "James",
    lastName: "Brown",
    username: "james.brown",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-04-01",
    updatedAt: "2023-04-02",
  },
  {
    id: "admin9988776655",
    firstName: "Olivia",
    lastName: "Wilson",
    username: "olivia.wilson",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-04-10",
    updatedAt: "2023-04-12",
  },
  {
    id: "admin5566778899",
    firstName: "William",
    lastName: "Taylor",
    username: "william.taylor",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-05-01",
    updatedAt: "2023-05-03",
  },
  {
    id: "admin2233445566",
    firstName: "Sophia",
    lastName: "Anderson",
    username: "sophia.anderson",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-05-15",
    updatedAt: "2023-05-20",
  },
  {
    id: "admin6677889900",
    firstName: "Daniel",
    lastName: "Thomas",
    username: "daniel.thomas",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-06-01",
    updatedAt: "2023-06-02",
  },
  {
    id: "admin3344556677",
    firstName: "Isabella",
    lastName: "Martinez",
    username: "isabella.martinez",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-06-15",
    updatedAt: "2023-06-16",
  },
  {
    id: "admin4455667788",
    firstName: "David",
    lastName: "Garcia",
    username: "david.garcia",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-07-01",
    updatedAt: "2023-07-03",
  },
  {
    id: "admin7788990011",
    firstName: "Mia",
    lastName: "Hernandez",
    username: "mia.hernandez",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-07-10",
    updatedAt: "2023-07-11",
  },
  {
    id: "admin8899001122",
    firstName: "Alexander",
    lastName: "Lopez",
    username: "alexander.lopez",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-08-01",
    updatedAt: "2023-08-02",
  },
  {
    id: "admin9900112233",
    firstName: "Charlotte",
    lastName: "Gonzalez",
    username: "charlotte.gonzalez",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-08-15",
    updatedAt: "2023-08-17",
  },
  {
    id: "admin123443211234",
    firstName: "Benjamin",
    lastName: "Perez",
    username: "benjamin.perez",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-09-01",
    updatedAt: "2023-09-02",
  },
  {
    id: "admin432112344321",
    firstName: "Amelia",
    lastName: "Lee",
    username: "amelia.lee",
    password: "hashed_admin_password",
    role: "admin",
    createdAt: "2023-09-20",
    updatedAt: "2023-09-21",
  },
];

export const PRODUCTS_MOCK_DATA = [
  {
    id: "prod001",
    name: "Product 1",
    rate: 4.5,
    quantity: 100,

    media: [
      {
        src: "https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
        title: "Fern",
      },
      {
        src: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f",
        title: "Snacks",
      },
      {
        src: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25",
        title: "Mushrooms",
      },
    ],

    reviews: [],
    categories: [
      {
        id: "cat001",
        name: "Category 1",
        slug: "category-1",
      },
      {
        id: "cat002",
        name: "Category 2",
        slug: "category-2",
      },
    ],
    tags: [
      { id: "tag001", name: "tag001", slug: "tag-001" },
      { id: "tag002", name: "tag002", slug: "tag-002" },
    ],
    brand: {
      id: "brand001",
      name: "Brand 1",
      slug: "brand-1",
    },
    relatedProducts: [],
    isInCampaign: false,
    isActive: true,
    visits: 150,
    isFeatured: true,
    catalogue: { id: "cat001", translations: { name: "Category 1" } },
    sold: 75,
    createdAt: "2023-01-01",
    updatedAt: "2023-01-02",
    lang: "en",
    name: "Product 1",
    slug: "product-1",
    excerpt: "Description for Product 1",
    price: { amount: 29.99, currency: "$" },
    discount: { amount: 5, type: "percentage", priceAfterDiscount: 28.49 },
    colors: [
      { name: "Red", code: "#FF0000" },
      { name: "Blue", code: "#0000FF" },
      { name: "Green", code: "#00FF00" },
    ],
    sizes: [
      { name: "Small", code: "S" },
      { name: "Medium", code: "M" },
      { name: "Large", code: "L" },
    ],
    description: `<p>This is a detailed description of Product 1. It includes all the features and benefits of the product.</p> <ul> <li>Feature 1</li> </ul>`,
    technicalDetails: {
      weight: "1kg",
      dimensions: "10x20x30cm",
      material: "Plastic",
      warranty: "2 years",
    },
    seo: {
      title: "Product 1 - Buy Now",
      description: "Get the best deal on Product 1.",
      keywords: ["product 1", "buy product 1", "best product 1"],
      ogTitle: "Product 1",
      ogDescription: "Get the best deal on Product 1.",
      ogImage: "https://example.com/images/product-1-og.jpg",
      twitterTitle: "Product 1",
      twitterDescription: "Get the best deal on Product 1.",
      twitterImage: "https://example.com/images/product-1-twitter.jpg",
      canonical: "https://example.com/products/product-1",
      robots: "index, follow",
      additionalMetaTags: [
        { property: "fb:app_id", content: "123456789" },
        { property: "twitter:card", content: "summary_large_image" },
      ],
    },
    translations: [
      {
        lang: "en",
        name: "Product 1",
        slug: "product-1",
        excerpt: "Description for Product 1",
        price: { amount: 29.99, currency: "$" },
        discount: { amount: 5, type: "percentage", priceAfterDiscount: 28.49 },
        colors: [
          { name: "Red", code: "#FF0000" },
          { name: "Blue", code: "#0000FF" },
          { name: "Green", code: "#00FF00" },
        ],
        sizes: [
          { name: "Small", code: "S" },
          { name: "Medium", code: "M" },
          { name: "Large", code: "L" },
        ],
        description: `<p>This is a detailed description of Product 1. It includes all the features and benefits of the product.</p> <ul> <li>Feature 1</li> </ul>`,
        technicalDetails: {
          weight: "1kg",
          dimensions: "10x20x30cm",
          material: "Plastic",
          warranty: "2 years",
        },
        seo: {
          title: "Product 1 - Buy Now",
          description: "Get the best deal on Product 1.",
          keywords: ["product 1", "buy product 1", "best product 1"],
          ogTitle: "Product 1",
          ogDescription: "Get the best deal on Product 1.",
          ogImage: "https://example.com/images/product-1-og.jpg",
          twitterTitle: "Product 1",
          twitterDescription: "Get the best deal on Product 1.",
          twitterImage: "https://example.com/images/product-1-twitter.jpg",
          canonical: "https://example.com/products/product-1",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
      {
        lang: "pt",
        name: "Produit 1",
        slug: "produit-1",
        excerpt: "Description du Produit 1",
        price: { amount: 25.99, currency: "€" },
        discount: { amount: 3, type: "fixed", priceAfterDiscount: 22.99 },
        colors: [
          { name: "Rouge", code: "#FF0000" },
          { name: "Bleu", code: "#0000FF" },
          { name: "Vert", code: "#00FF00" },
        ],
        sizes: [
          { name: "Petit", code: "P" },
          { name: "Moyen", code: "M" },
          { name: "Grand", code: "G" },
        ],
        description: `<p>Ceci est une description détaillée du Produit 1. Il comprend toutes les caractéristiques et avantages du produit.</p> <ul> <li>Caractéristique 1</li> </ul>`,
        technicalDetails: {
          weight: "1kg",
          dimensions: "10x20x30cm",
          material: "Plastic",
          warranty: "2 years",
        },
        seo: {
          title: "Produit 1 - Achetez Maintenant",
          description: "Obtenez la meilleure offre sur le Produit 1.",
          keywords: ["produit 1", "acheter produit 1", "meilleur produit 1"],
          ogTitle: "Produit 1",
          ogDescription: "Obtenez la meilleure offre sur le Produit 1.",
          ogImage: "https://example.com/images/produit-1-og.jpg",
          twitterTitle: "Produit 1",
          twitterDescription: "Obtenez la meilleure offre sur le Produit 1.",
          twitterImage: "https://example.com/images/produit-1-twitter.jpg",
          canonical: "https://example.com/fr/produits/produit-1",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
      {
        lang: "ar",
        name: "منتج 1",
        slug: "منتج-1",
        excerpt: "وصف لمنتج 1",
        price: { amount: 250, currency: "UAD" },
        discount: { amount: 20, type: "fixed", priceAfterDiscount: 230 },
        colors: [
          { name: "أحمر", code: "#FF0000" },
          { name: "أزرق", code: "#0000FF" },
          { name: "أخضر", code: "#00FF00" },
        ],
        sizes: [
          { name: "صغير", code: "ص" },
          { name: "متوسط", code: "م" },
          { name: "كبير", code: "ك" },
        ],
        description: `<p>هذا وصف تفصيلي للمنتج 1. يتضمن جميع ميزات وفوائد المنتج.</p> <ul> <li>الميزة 1</li> </ul>`,
        technicalDetails: {
          weight: "1kg",
          dimensions: "10x20x30cm",
          material: "Plastic",
          warranty: "2 years",
        },
        seo: {
          title: "منتج 1 - اشتري الآن",
          description: "احصل على أفضل صفقة على المنتج 1.",
          keywords: ["منتج 1", "شراء منتج 1", "أفضل منتج 1"],
          ogTitle: "منتج 1",
          ogDescription: "احصل على أفضل صفقة على المنتج 1.",
          ogImage: "https://example.com/images/product-1-og.jpg",
          twitterTitle: "منتج 1",
          twitterDescription: "احصل على أفضل صفقة على المنتج 1.",
          twitterImage: "https://example.com/images/product-1-twitter.jpg",
          canonical: "https://example.com/ar/products/product-1",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
      {
        lang: "fa",
        name: "محصول 1",
        slug: "محصول-1",
        excerpt: "توضیحات برای محصول 1",
        price: { amount: 29000000, currency: "ريال" },
        discount: {
          amount: 500000,
          type: "fixed",
          priceAfterDiscount: 28500000,
        },
        colors: [
          { name: "قرمز", code: "#FF0000" },
          { name: "آبی", code: "#0000FF" },
          { name: "سبز", code: "#00FF00" },
        ],
        sizes: [
          { name: "کوچک", code: "ک" },
          { name: "متوسط", code: "م" },
          { name: "بزرگ", code: "ب" },
        ],
        description: `<p>این یک توضیح مفصل از محصول 1 است. شامل تمام ویژگی‌ها و مزایای محصول می‌باشد.</p> <ul> <li>ویژگی 1</li> </ul>`,
        technicalDetails: {
          weight: "1kg",
          dimensions: "10x20x30cm",
          material: "Plastic",
          warranty: "2 years",
        },
        seo: {
          title: "محصول 1 - هم اکنون خرید کنید",
          description: "بهترین پیشنهادات را برای محصول 1 دریافت کنید.",
          keywords: ["محصول 1", "خرید محصول 1", "بهترین محصول 1"],
          ogTitle: "محصول 1",
          ogDescription: "بهترین پیشنهادات را برای محصول 1 دریافت کنید.",
          ogImage: "https://example.com/images/product-1-og.jpg",
          twitterTitle: "محصول 1",
          twitterDescription: "بهترین پیشنهادات را برای محصول 1 دریافت کنید.",
          twitterImage: "https://example.com/images/product-1-twitter.jpg",
          canonical: "https://example.com/fa/products/product-1",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },

  {
    id: "prod002",
    name: "Product 2",
    rate: 4.2,
    quantity: 80,

    media: [
      {
        src: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
        title: "Headphones",
      },
      {
        src: "https://images.unsplash.com/photo-1512499617640-c2f999098c8e",
        title: "Music Setup",
      },
    ],

    reviews: [],
    categories: [
      {
        id: "cat003",
        name: "Category 3",
        slug: "category-3",
      },
      {
        id: "cat004",
        name: "Category 4",
        slug: "category-4",
      },
    ],
    tags: [
      { id: "tag003", name: "tag003", slug: "tag-003" },
      { id: "tag004", name: "tag004", slug: "tag-004" },
    ],
    brand: {
      id: "brand002",
      name: "Brand 2",
      slug: "brand-2",
    },
    relatedProducts: ["prod001"],
    isInCampaign: true,
    isActive: true,
    visits: 95,
    isFeatured: false,
    catalogue: { id: "cat003", translations: { name: "Category 3" } },
    sold: 40,
    createdAt: "2023-02-05",
    updatedAt: "2023-02-06",
    lang: "en",
    name: "Product 2",
    slug: "product-2",
    excerpt: "Description for Product 2",
    price: { amount: 59.99, currency: "$" },
    discount: { amount: 10, type: "percentage", priceAfterDiscount: 53.99 },
    colors: [
      { name: "Black", code: "#000000" },
      { name: "White", code: "#FFFFFF" },
    ],
    sizes: [],
    description: `<p>This is a detailed description of Product 2. Great audio quality and comfort.</p>`,
    technicalDetails: {
      weight: "0.5kg",
      dimensions: "20x15x10cm",
      material: "Metal & Plastic",
      warranty: "1 year",
    },
    seo: {
      title: "Product 2 - Buy Now",
      description: "High-quality headphones Product 2.",
      keywords: ["product 2", "buy headphones", "best headphones"],
      ogTitle: "Product 2",
      ogDescription: "High-quality headphones Product 2.",
      ogImage: "https://example.com/images/product-2-og.jpg",
      twitterTitle: "Product 2",
      twitterDescription: "High-quality headphones Product 2.",
      twitterImage: "https://example.com/images/product-2-twitter.jpg",
      canonical: "https://example.com/products/product-2",
      robots: "index, follow",
      additionalMetaTags: [
        { property: "fb:app_id", content: "123456789" },
        { property: "twitter:card", content: "summary_large_image" },
      ],
    },
    translations: [
      {
        lang: "en",
        name: "Product 2",
        slug: "product-2",
        excerpt: "Description for Product 2",
        price: { amount: 59.99, currency: "$" },
        discount: { amount: 10, type: "percentage", priceAfterDiscount: 53.99 },
        colors: [
          { name: "Black", code: "#000000" },
          { name: "White", code: "#FFFFFF" },
        ],
        sizes: [],
        description: `<p>This is a detailed description of Product 2. Great audio quality and comfort.</p>`,
        technicalDetails: {
          weight: "0.5kg",
          dimensions: "20x15x10cm",
          material: "Metal & Plastic",
          warranty: "1 year",
        },
        seo: {
          title: "Product 2 - Buy Now",
          description: "High-quality headphones Product 2.",
          keywords: ["product 2", "buy headphones", "best headphones"],
          ogTitle: "Product 2",
          ogDescription: "High-quality headphones Product 2.",
          ogImage: "https://example.com/images/product-2-og.jpg",
          twitterTitle: "Product 2",
          twitterDescription: "High-quality headphones Product 2.",
          twitterImage: "https://example.com/images/product-2-twitter.jpg",
          canonical: "https://example.com/products/product-2",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
      {
        lang: "pt",
        name: "Produit 2",
        slug: "produit-2",
        excerpt: "Description du Produit 2",
        price: { amount: 50.99, currency: "€" },
        discount: { amount: 5, type: "fixed", priceAfterDiscount: 45.99 },
        colors: [
          { name: "Noir", code: "#000000" },
          { name: "Blanc", code: "#FFFFFF" },
        ],
        sizes: [],
        description: `<p>Ceci est une description détaillée du Produit 2. Qualité audio supérieure.</p>`,
        technicalDetails: {
          weight: "0.5kg",
          dimensions: "20x15x10cm",
          material: "Metal & Plastic",
          warranty: "1 year",
        },
        seo: {
          title: "Produit 2 - Achetez Maintenant",
          description: "Casque audio de haute qualité.",
          keywords: ["produit 2", "acheter casque", "meilleur casque"],
          ogTitle: "Produit 2",
          ogDescription: "Casque audio de haute qualité.",
          ogImage: "https://example.com/images/produit-2-og.jpg",
          twitterTitle: "Produit 2",
          twitterDescription: "Casque audio de haute qualité.",
          twitterImage: "https://example.com/images/produit-2-twitter.jpg",
          canonical: "https://example.com/fr/produits/produit-2",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
      {
        lang: "ar",
        name: "منتج 2",
        slug: "منتج-2",
        excerpt: "وصف لمنتج 2",
        price: { amount: 500, currency: "UAD" },
        discount: { amount: 50, type: "fixed", priceAfterDiscount: 450 },
        colors: [
          { name: "أسود", code: "#000000" },
          { name: "أبيض", code: "#FFFFFF" },
        ],
        sizes: [],
        description: `<p>هذا وصف تفصيلي للمنتج 2. جودة صوت ممتازة وراحة.</p>`,
        technicalDetails: {
          weight: "0.5kg",
          dimensions: "20x15x10cm",
          material: "Metal & Plastic",
          warranty: "1 year",
        },
        seo: {
          title: "منتج 2 - اشتري الآن",
          description: "سماعات عالية الجودة.",
          keywords: ["منتج 2", "شراء سماعات", "أفضل سماعات"],
          ogTitle: "منتج 2",
          ogDescription: "سماعات عالية الجودة.",
          ogImage: "https://example.com/images/product-2-og.jpg",
          twitterTitle: "منتج 2",
          twitterDescription: "سماعات عالية الجودة.",
          twitterImage: "https://example.com/images/product-2-twitter.jpg",
          canonical: "https://example.com/ar/products/product-2",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
      {
        lang: "fa",
        name: "محصول 2",
        slug: "محصول-2",
        excerpt: "توضیحات برای محصول 2",
        price: { amount: 59000000, currency: "ريال" },
        discount: {
          amount: 1000000,
          type: "fixed",
          priceAfterDiscount: 58000000,
        },
        colors: [
          { name: "مشکی", code: "#000000" },
          { name: "سفید", code: "#FFFFFF" },
        ],
        sizes: [],
        description: `<p>این یک توضیح مفصل از محصول 2 است. کیفیت صدای عالی و راحتی فوق‌العاده.</p>`,
        technicalDetails: {
          weight: "0.5kg",
          dimensions: "20x15x10cm",
          material: "Metal & Plastic",
          warranty: "1 year",
        },
        seo: {
          title: "محصول 2 - هم اکنون خرید کنید",
          description: "سماعات با کیفیت عالی.",
          keywords: ["محصول 2", "خرید سماعات", "بهترین سماعات"],
          ogTitle: "محصول 2",
          ogDescription: "سماعات با کیفیت عالی.",
          ogImage: "https://example.com/images/product-2-og.jpg",
          twitterTitle: "محصول 2",
          twitterDescription: "سماعات با کیفیت عالی.",
          twitterImage: "https://example.com/images/product-2-twitter.jpg",
          canonical: "https://example.com/fa/products/product-2",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },

  {
    id: "prod003",
    name: "Product 3",
    rate: 4.8,
    quantity: 200,

    media: [
      {
        src: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
        title: "Laptop",
      },
      {
        src: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
        title: "Workspace",
      },
    ],

    reviews: [],
    categories: [
      {
        id: "cat005",
        name: "Category 5",
        slug: "category-5",
      },
    ],
    tags: [
      { id: "tag005", name: "tag005", slug: "tag-005" },
      { id: "tag006", name: "tag006", slug: "tag-006" },
    ],
    brand: {
      id: "brand003",
      name: "Brand 3",
      slug: "brand-3",
    },
    relatedProducts: ["prod001", "prod002"],
    isInCampaign: false,
    isActive: true,
    visits: 320,
    isFeatured: true,
    catalogue: { id: "cat005", translations: { name: "Category 5" } },
    sold: 150,
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    lang: "en",
    name: "Product 3",
    slug: "product-3",
    excerpt: "Description for Product 3",
    price: { amount: 899.99, currency: "$" },
    discount: { amount: 50, type: "fixed", priceAfterDiscount: 849.99 },
    colors: [
      { name: "Silver", code: "#C0C0C0" },
      { name: "Gray", code: "#808080" },
    ],
    sizes: [],
    description: `<p>This is a detailed description of Product 3. A powerful laptop for work and play.</p>`,
    technicalDetails: {
      weight: "2kg",
      dimensions: "30x20x2cm",
      material: "Aluminum",
      warranty: "3 years",
    },
    seo: {
      title: "Product 3 - Buy Now",
      description: "High-performance laptop Product 3.",
      keywords: ["product 3", "buy laptop", "best laptop"],
      ogTitle: "Product 3",
      ogDescription: "High-performance laptop Product 3.",
      ogImage: "https://example.com/images/product-3-og.jpg",
      twitterTitle: "Product 3",
      twitterDescription: "High-performance laptop Product 3.",
      twitterImage: "https://example.com/images/product-3-twitter.jpg",
      canonical: "https://example.com/products/product-3",
      robots: "index, follow",
      additionalMetaTags: [
        { property: "fb:app_id", content: "123456789" },
        { property: "twitter:card", content: "summary_large_image" },
      ],
    },
    translations: [
      {
        lang: "en",
        name: "Product 3",
        slug: "product-3",
        excerpt: "Description for Product 3",
        price: { amount: 899.99, currency: "$" },
        discount: { amount: 50, type: "fixed", priceAfterDiscount: 849.99 },
        colors: [
          { name: "Silver", code: "#C0C0C0" },
          { name: "Gray", code: "#808080" },
        ],
        sizes: [],
        description: `<p>This is a detailed description of Product 3. A powerful laptop for work and play.</p>`,
        technicalDetails: {
          weight: "2kg",
          dimensions: "30x20x2cm",
          material: "Aluminum",
          warranty: "3 years",
        },
        seo: {
          title: "Product 3 - Buy Now",
          description: "High-performance laptop Product 3.",
          keywords: ["product 3", "buy laptop", "best laptop"],
          ogTitle: "Product 3",
          ogDescription: "High-performance laptop Product 3.",
          ogImage: "https://example.com/images/product-3-og.jpg",
          twitterTitle: "Product 3",
          twitterDescription: "High-performance laptop Product 3.",
          twitterImage: "https://example.com/images/product-3-twitter.jpg",
          canonical: "https://example.com/products/product-3",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
      {
        lang: "pt",
        name: "Produit 3",
        slug: "produit-3",
        excerpt: "Description du Produit 3",
        price: { amount: 799.99, currency: "€" },
        discount: { amount: 30, type: "fixed", priceAfterDiscount: 769.99 },
        colors: [
          { name: "Argent", code: "#C0C0C0" },
          { name: "Gris", code: "#808080" },
        ],
        sizes: [],
        description: `<p>Ceci est une description détaillée du Produit 3. Un ordinateur portable puissant.</p>`,
        technicalDetails: {
          weight: "2kg",
          dimensions: "30x20x2cm",
          material: "Aluminum",
          warranty: "3 years",
        },
        seo: {
          title: "Produit 3 - Achetez Maintenant",
          description: "Ordinateur portable haute performance.",
          keywords: ["produit 3", "acheter ordinateur portable", "meilleur pc"],
          ogTitle: "Produit 3",
          ogDescription: "Ordinateur portable haute performance.",
          ogImage: "https://example.com/images/produit-3-og.jpg",
          twitterTitle: "Produit 3",
          twitterDescription: "Ordinateur portable haute performance.",
          twitterImage: "https://example.com/images/produit-3-twitter.jpg",
          canonical: "https://example.com/fr/produits/produit-3",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
      {
        lang: "ar",
        name: "منتج 3",
        slug: "منتج-3",
        excerpt: "وصف لمنتج 3",
        price: { amount: 3500, currency: "UAD" },
        discount: { amount: 200, type: "fixed", priceAfterDiscount: 3300 },
        colors: [
          { name: "فضي", code: "#C0C0C0" },
          { name: "رمادي", code: "#808080" },
        ],
        sizes: [],
        description: `<p>هذا وصف تفصيلي للمنتج 3. كمبيوتر محمول قوي.</p>`,
        technicalDetails: {
          weight: "2kg",
          dimensions: "30x20x2cm",
          material: "Aluminum",
          warranty: "3 years",
        },
        seo: {
          title: "منتج 3 - اشتري الآن",
          description: "كمبيوتر محمول عالي الأداء.",
          keywords: ["منتج 3", "شراء كمبيوتر محمول", "أفضل كمبيوتر محمول"],
          ogTitle: "منتج 3",
          ogDescription: "كمبيوتر محمول عالي الأداء.",
          ogImage: "https://example.com/images/product-3-og.jpg",
          twitterTitle: "منتج 3",
          twitterDescription: "كمبيوتر محمول عالي الأداء.",
          twitterImage: "https://example.com/images/product-3-twitter.jpg",
          canonical: "https://example.com/ar/products/product-3",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
      {
        lang: "fa",
        name: "محصول 3",
        slug: "محصول-3",
        excerpt: "توضیحات برای محصول 3",
        price: { amount: 890000000, currency: "ريال" },
        discount: {
          amount: 50000000,
          type: "fixed",
          priceAfterDiscount: 840000000,
        },
        colors: [
          { name: "نقره‌ای", code: "#C0C0C0" },
          { name: "خاکستری", code: "#808080" },
        ],
        sizes: [],
        description: `<p>این یک توضیح مفصل از محصول 3 است. لپ‌تاپ قدرتمند برای کار و بازی.</p>`,
        technicalDetails: {
          weight: "2kg",
          dimensions: "30x20x2cm",
          material: "Aluminum",
          warranty: "3 years",
        },
        seo: {
          title: "محصول 3 - هم اکنون خرید کنید",
          description: "لپ‌تاپ با عملکرد بالا.",
          keywords: ["محصول 3", "خرید لپ‌تاپ", "بهترین لپ‌تاپ"],
          ogTitle: "محصول 3",
          ogDescription: "لپ‌تاپ با عملکرد بالا.",
          ogImage: "https://example.com/images/product-3-og.jpg",
          twitterTitle: "محصول 3",
          twitterDescription: "لپ‌تاپ با عملکرد بالا.",
          twitterImage: "https://example.com/images/product-3-twitter.jpg",
          canonical: "https://example.com/fa/products/product-3",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
];

export const CATEGORIES_MOCK_DATA = [
  {
    id: "cat_id_1",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
        title: "Fern",
      },
      {
        src: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
        title: "Moss",
      },
      {
        src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
        title: "Palm",
      },
    ],
    image: {
      src: "https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
      title: "Fern",
    },
    icon: { src: "", title: "" },
    subCategories: ["cat_1", "cat_2"],
    tags: [],
    isActive: true,
    slug: "fern-category",
    name: "Fern",
    excerpt: "Beautiful fern plants",
    description: "<p>Explanations about Fern category...</p>",
    createdAt: "2023-09-20",
    updatedAt: "2023-09-21",
    translations: [
      {
        lang: "us",
        slug: "fern-category",
        name: "Fern",
        excerpt: "Beautiful fern plants",
        description: "<p>Explanations about Fern category...</p>",
        seo: {
          title: "Fern Category",
          description: "Discover our Fern plants",
          keywords: ["fern", "plants", "greenery"],
          ogTitle: "Fern Category",
          ogDescription: "Beautiful Ferns available",
          ogImage: "",
          twitterTitle: "Fern Category",
          twitterDescription: "Beautiful Ferns available",
          twitterImage: "",
          canonical: "",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
  {
    id: "cat_id_2",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8",
        title: "Cactus",
      },
      {
        src: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
        title: "Succulent",
      },
    ],
    image: {
      src: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8",
      title: "Cactus",
    },
    icon: { src: "", title: "" },
    subCategories: ["cat_1", "cat_2"],
    tags: [],
    isActive: true,
    createdAt: "2023-09-20",
    updatedAt: "2023-09-21",
    slug: "cactus-category",
    name: "Cactus",
    excerpt: "Low maintenance cacti",
    description: "<p>Explanations about Cactus category...</p>",
    translations: [
      {
        lang: "us",
        slug: "cactus-category",
        name: "Cactus",
        excerpt: "Low maintenance cacti",
        description: "<p>Explanations about Cactus category...</p>",
        seo: {
          title: "Cactus Category",
          description: "Discover our cacti plants",
          keywords: ["cactus", "plants", "succulent"],
          ogTitle: "Cactus Category",
          ogDescription: "Beautiful Cacti available",
          ogImage: "",
          twitterTitle: "Cactus Category",
          twitterDescription: "Beautiful Cacti available",
          twitterImage: "",
          canonical: "",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
  {
    id: "cat_id_3",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1482192505345-5655af888cc4",
        title: "Orchid",
      },
    ],
    image: {
      src: "https://images.unsplash.com/photo-1482192505345-5655af888cc4",
      title: "Orchid",
    },
    icon: { src: "", title: "" },
    subCategories: ["cat_1", "cat_2"],
    tags: [],
    isActive: true,
    createdAt: "2023-09-20",
    updatedAt: "2023-09-21",
    slug: "orchid-category",
    name: "Orchid",
    excerpt: "Elegant orchids for home",
    description: "<p>Explanations about Orchid category...</p>",
    translations: [
      {
        lang: "us",
        slug: "orchid-category",
        name: "Orchid",
        excerpt: "Elegant orchids for home",
        description: "<p>Explanations about Orchid category...</p>",
        seo: {
          title: "Orchid Category",
          description: "Discover our Orchid plants",
          keywords: ["orchid", "flowers", "elegant"],
          ogTitle: "Orchid Category",
          ogDescription: "Elegant Orchids available",
          ogImage: "",
          twitterTitle: "Orchid Category",
          twitterDescription: "Elegant Orchids available",
          twitterImage: "",
          canonical: "",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
  {
    id: "cat_id_4",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
        title: "Bonsai",
      },
    ],
    image: {
      src: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
      title: "Bonsai",
    },
    icon: { src: "", title: "" },
    subCategories: ["cat_1", "cat_2"],
    tags: [],
    isActive: true,
    createdAt: "2023-09-20",
    updatedAt: "2023-09-21",
    slug: "bonsai-category",
    name: "Bonsai",
    excerpt: "Miniature Bonsai trees",
    description: "<p>Explanations about Bonsai category...</p>",
    translations: [
      {
        lang: "us",
        slug: "bonsai-category",
        name: "Bonsai",
        excerpt: "Miniature Bonsai trees",
        description: "<p>Explanations about Bonsai category...</p>",
        seo: {
          title: "Bonsai Category",
          description: "Discover our Bonsai trees",
          keywords: ["bonsai", "miniature", "trees"],
          ogTitle: "Bonsai Category",
          ogDescription: "Miniature Bonsai trees available",
          ogImage: "",
          twitterTitle: "Bonsai Category",
          twitterDescription: "Miniature Bonsai trees available",
          twitterImage: "",
          canonical: "",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
  {
    id: "cat_id_5",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
        title: "Palm Tree",
      },
    ],
    image: {
      src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
      title: "Palm Tree",
    },
    icon: { src: "", title: "" },
    subCategories: ["cat_1", "cat_2"],
    tags: [],
    isActive: true,
    createdAt: "2023-09-20",
    updatedAt: "2023-09-21",
    slug: "palm-tree-category",
    name: "Palm Tree",
    excerpt: "Tropical palm trees",
    description: "<p>Explanations about Palm Tree category...</p>",
    translations: [
      {
        lang: "us",
        slug: "palm-tree-category",
        name: "Palm Tree",
        excerpt: "Tropical palm trees",
        description: "<p>Explanations about Palm Tree category...</p>",
        seo: {
          title: "Palm Tree Category",
          description: "Discover our Palm Trees",
          keywords: ["palm", "tree", "tropical"],
          ogTitle: "Palm Tree Category",
          ogDescription: "Tropical Palm Trees available",
          ogImage: "",
          twitterTitle: "Palm Tree Category",
          twitterDescription: "Tropical Palm Trees available",
          twitterImage: "",
          canonical: "",
          robots: "index, follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
];

export const BRANDS_MOCK_DATA = [
  {
    id: "BRND_1",
    image: {
      src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
      title: "Palm Tree",
    },
    tags: [],
    categories: [],
    slug: "palm-tree",
    name: "Palm Tree",
    excerpt: "Tropical and natural brand style.",
    description: "<p>Explanations about Palm Tree brand.</p>",
    isSelected: false,
    isActive: true,
    translations: [
      {
        lang: "us",
        slug: "palm-tree",
        name: "Palm Tree",
        excerpt: "Tropical and natural brand style.",
        description: "<p>Explanations about Palm Tree brand.</p>",
        seo: {
          title: "Palm Tree Brand",
          description:
            "Discover the Palm Tree brand – tropical, fresh, and sustainable.",
          keywords: ["palm", "tree", "brand", "nature"],
          ogTitle: "Palm Tree Brand",
          ogDescription: "Explore Palm Tree brand products.",
          ogImage:
            "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
          twitterTitle: "Palm Tree Brand",
          twitterDescription: "Explore Palm Tree brand products.",
          twitterImage:
            "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
          canonical: "https://example.com/brands/palm-tree",
          robots: "index,follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
  {
    id: "BRND_2",
    image: {
      src: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
      title: "SoundWave",
    },
    tags: [],
    categories: [],
    slug: "soundwave",
    name: "SoundWave",
    excerpt: "Premium audio and lifestyle brand.",
    description: "<p>Explanations about SoundWave brand.</p>",
    isSelected: false,
    isActive: true,
    translations: [
      {
        lang: "us",
        slug: "soundwave",
        name: "SoundWave",
        excerpt: "Premium audio and lifestyle brand.",
        description: "<p>Explanations about SoundWave brand.</p>",
        seo: {
          title: "SoundWave Brand",
          description: "Discover high-quality sound and lifestyle products.",
          keywords: ["sound", "audio", "headphones", "brand"],
          ogTitle: "SoundWave Brand",
          ogDescription: "Explore premium audio experiences.",
          ogImage:
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
          twitterTitle: "SoundWave Brand",
          twitterDescription: "Premium sound for everyone.",
          twitterImage:
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
          canonical: "https://example.com/brands/soundwave",
          robots: "index,follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
  {
    id: "BRND_3",
    image: {
      src: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
      title: "LensCraft",
    },
    tags: [],
    categories: [],
    slug: "lenscraft",
    name: "LensCraft",
    excerpt: "Photography gear and accessories brand.",
    description: "<p>Explanations about LensCraft brand.</p>",
    isSelected: false,
    isActive: true,
    translations: [
      {
        lang: "us",
        slug: "lenscraft",
        name: "LensCraft",
        excerpt: "Photography gear and accessories brand.",
        description: "<p>Explanations about LensCraft brand.</p>",
        seo: {
          title: "LensCraft Brand",
          description:
            "Professional photography gear and creative accessories.",
          keywords: ["lens", "camera", "brand", "photography"],
          ogTitle: "LensCraft Brand",
          ogDescription: "Capture moments with LensCraft.",
          ogImage:
            "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
          twitterTitle: "LensCraft Brand",
          twitterDescription: "Photography gear for creators.",
          twitterImage:
            "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
          canonical: "https://example.com/brands/lenscraft",
          robots: "index,follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
  {
    id: "BRND_4",
    image: {
      src: "https://images.unsplash.com/photo-1581291519195-ef11498d1cf5",
      title: "UrbanWear",
    },
    tags: [],
    categories: [],
    slug: "urbanwear",
    name: "UrbanWear",
    excerpt: "Street fashion and modern lifestyle brand.",
    description: "<p>Explanations about UrbanWear brand.</p>",
    isSelected: false,
    isActive: true,
    translations: [
      {
        lang: "us",
        slug: "urbanwear",
        name: "UrbanWear",
        excerpt: "Street fashion and modern lifestyle brand.",
        description: "<p>Explanations about UrbanWear brand.</p>",
        seo: {
          title: "UrbanWear Brand",
          description: "Trendy streetwear and fashion essentials.",
          keywords: ["urban", "fashion", "brand", "clothing"],
          ogTitle: "UrbanWear Brand",
          ogDescription: "Discover trendy streetwear.",
          ogImage:
            "https://images.unsplash.com/photo-1581291519195-ef11498d1cf5",
          twitterTitle: "UrbanWear Brand",
          twitterDescription: "Modern fashion for everyone.",
          twitterImage:
            "https://images.unsplash.com/photo-1581291519195-ef11498d1cf5",
          canonical: "https://example.com/brands/urbanwear",
          robots: "index,follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
  {
    id: "BRND_5",
    image: {
      src: "https://images.unsplash.com/photo-1503264116251-35a269479413",
      title: "EcoRide",
    },
    tags: [],
    categories: ["cat_1, cat_2"],
    slug: "ecoride",
    name: "EcoRide",
    excerpt: "Sustainable mobility and eco-friendly bikes.",
    description: "<p>Explanations about EcoRide brand.</p>",
    isSelected: false,
    isActive: true,
    translations: [
      {
        slug: "ecoride",
        name: "EcoRide",
        excerpt: "Sustainable mobility and eco-friendly bikes.",
        description: "<p>Explanations about EcoRide brand.</p>",
        lang: "us",
        seo: {
          title: "EcoRide Brand",
          description: "Eco-friendly bikes and sustainable transportation.",
          keywords: ["eco", "bike", "ride", "sustainable"],
          ogTitle: "EcoRide Brand",
          ogDescription: "Ride green with EcoRide.",
          ogImage:
            "https://images.unsplash.com/photo-1503264116251-35a269479413",
          twitterTitle: "EcoRide Brand",
          twitterDescription: "Eco-friendly bikes for urban riders.",
          twitterImage:
            "https://images.unsplash.com/photo-1503264116251-35a269479413",
          canonical: "https://example.com/brands/ecoride",
          robots: "index,follow",
          additionalMetaTags: [
            { property: "fb:app_id", content: "123456789" },
            { property: "twitter:card", content: "summary_large_image" },
          ],
        },
      },
    ],
  },
];

export const ORDERS_MOCK_DATA = [
  {
    id: "ord_1",
    trackNumber: "1238091329",
    status: "delivered",
    submitDate: "2025-07-12",
    address: {},
    transaction: {},
    price: {
      amount: "750",
      currency: "$",
    },
    discount: {
      amount: "250",
      type: "amount",
    },
    shipmentPrice: {
      amount: "0",
      currency: "$",
    },
    finalCost: {
      amount: "500",
      currency: "$",
    },
    products: [],
    user: "usr_1",
    shipmentDate: "2025-07-18",
    shipmentTrackNumber: "78234789342789",
  },
  {
    id: "ord_2",
    trackNumber: "9876543210",
    status: "pending",
    submitDate: "2025-08-01",
    address: {},
    transaction: {},
    price: {
      amount: "1200",
      currency: "$",
    },
    discount: {
      amount: "0",
      type: "amount",
    },
    shipmentPrice: {
      amount: "30",
      currency: "$",
    },
    finalCost: {
      amount: "1230",
      currency: "$",
    },
    products: [],
    user: "usr_2",
    shipmentDate: "2025-08-07",
    shipmentTrackNumber: "998877665544",
  },
  {
    id: "ord_3",
    trackNumber: "5678901234",
    status: "shipping",
    submitDate: "2025-06-20",
    address: {},
    transaction: {},
    price: {
      amount: "540",
      currency: "$",
    },
    discount: {
      amount: "40",
      type: "amount",
    },
    shipmentPrice: {
      amount: "15",
      currency: "$",
    },
    finalCost: {
      amount: "515",
      currency: "$",
    },
    products: [],
    user: "usr_3",
    shipmentDate: "2025-06-25",
    shipmentTrackNumber: "334455667788",
  },
  {
    id: "ord_4",
    trackNumber: "2468135790",
    status: "canceled",
    submitDate: "2025-09-05",
    address: {},
    transaction: {},
    price: {
      amount: "300",
      currency: "$",
    },
    discount: {
      amount: "30",
      type: "amount",
    },
    shipmentPrice: {
      amount: "10",
      currency: "$",
    },
    finalCost: {
      amount: "280",
      currency: "$",
    },
    products: [],
    user: "usr_4",
    shipmentDate: "2025-09-08",
    shipmentTrackNumber: "112233445566",
  },
  {
    id: "ord_5",
    trackNumber: "1928374650",
    status: "processing",
    submitDate: "2025-07-28",
    address: {},
    transaction: {},
    price: {
      amount: "850",
      currency: "$",
    },
    discount: {
      amount: "85",
      type: "amount",
    },
    shipmentPrice: {
      amount: "25",
      currency: "$",
    },
    finalCost: {
      amount: "790",
      currency: "$",
    },
    products: [],
    user: "usr_5",
    shipmentDate: "2025-08-03",
    shipmentTrackNumber: "443322110099",
  },
  {
    id: "ord_6",
    trackNumber: "5647382910",
    status: "delivered",
    submitDate: "2025-05-15",
    address: {},
    transaction: {},
    price: {
      amount: "2000",
      currency: "$",
    },
    discount: {
      amount: "200",
      type: "amount",
    },
    shipmentPrice: {
      amount: "0",
      currency: "$",
    },
    finalCost: {
      amount: "1800",
      currency: "$",
    },
    products: [],
    user: "usr_6",
    shipmentDate: "2025-05-22",
    shipmentTrackNumber: "556677889900",
  },
  {
    id: "ord_7",
    trackNumber: "3141592653",
    status: "shipping",
    submitDate: "2025-09-10",
    address: {},
    transaction: {},
    price: {
      amount: "430",
      currency: "$",
    },
    discount: {
      amount: "0",
      type: "amount",
    },
    shipmentPrice: {
      amount: "20",
      currency: "$",
    },
    finalCost: {
      amount: "450",
      currency: "$",
    },
    products: [],
    user: "usr_7",
    shipmentDate: "2025-09-15",
    shipmentTrackNumber: "778899001122",
  },
  {
    id: "ord_8",
    trackNumber: "1029384756",
    status: "failed",
    submitDate: "2025-06-05",
    address: {},
    transaction: {},
    price: {
      amount: "150",
      currency: "$",
    },
    discount: {
      amount: "10",
      type: "amount",
    },
    shipmentPrice: {
      amount: "5",
      currency: "$",
    },
    finalCost: {
      amount: "145",
      currency: "$",
    },
    products: [],
    user: "usr_8",
    shipmentDate: "2025-06-10",
    shipmentTrackNumber: "667788990011",
  },
];

export const CARTS_MOCK_DATA = [
  {
    id: "cart_1",
    products: [PRODUCTS_MOCK_DATA[0], PRODUCTS_MOCK_DATA[1]],
    user: USERS_MOCK_DATA[0],
    coupon: {},
    suggestedProducts: [PRODUCTS_MOCK_DATA[2]],
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    price: { amount: "59.98", currency: "$" },
    discount: { amount: "5", currency: "$", type: "flat" },
    shipping: { amount: "7.99", currency: "$" },
    finalPrice: { amount: "62.97", currency: "$" },
  },
  {
    id: "cart_2",
    products: [PRODUCTS_MOCK_DATA[2]],
    user: USERS_MOCK_DATA[1],
    coupon: {},
    suggestedProducts: PRODUCTS_MOCK_DATA,
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    price: { amount: "29.99", currency: "$" },
    discount: { amount: "10", currency: "%", type: "percentage" },
    shipping: { amount: "5.99", currency: "$" },
    finalPrice: { amount: "32.99", currency: "$" },
  },
  {
    id: "cart_3",
    products: [PRODUCTS_MOCK_DATA[1], PRODUCTS_MOCK_DATA[2]],
    user: USERS_MOCK_DATA[2],
    coupon: {},
    suggestedProducts: [],
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    price: { amount: "74.5", currency: "$" },
    discount: { amount: "15", currency: "$", type: "flat" },
    shipping: { amount: "0", currency: "$" },
    finalPrice: { amount: "59.5", currency: "$" },
  },
  {
    id: "cart_4",
    products: [PRODUCTS_MOCK_DATA[1]],
    user: USERS_MOCK_DATA[3],
    coupon: {},
    suggestedProducts: [PRODUCTS_MOCK_DATA[1]],
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    price: { amount: "19.99", currency: "$" },
    discount: { amount: "0", currency: "$", type: "flat" },
    shipping: { amount: "4.99", currency: "$" },
    finalPrice: { amount: "24.98", currency: "$" },
  },
  {
    id: "cart_5",
    products: [PRODUCTS_MOCK_DATA[0], PRODUCTS_MOCK_DATA[2]],
    user: USERS_MOCK_DATA[4],
    coupon: {},
    suggestedProducts: [],
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    price: { amount: "89.98", currency: "$" },
    discount: { amount: "20", currency: "%", type: "percentage" },
    shipping: { amount: "9.99", currency: "$" },
    finalPrice: { amount: "81.99", currency: "$" },
  },
  {
    id: "cart_6",
    products: [PRODUCTS_MOCK_DATA[1]],
    user: USERS_MOCK_DATA[5],
    coupon: {},
    suggestedProducts: [],
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    price: { amount: "39.99", currency: "$" },
    discount: { amount: "5", currency: "$", type: "flat" },
    shipping: { amount: "7.5", currency: "$" },
    finalPrice: { amount: "42.49", currency: "$" },
  },
  {
    id: "cart_7",
    products: [PRODUCTS_MOCK_DATA[2], PRODUCTS_MOCK_DATA[1]],
    user: USERS_MOCK_DATA[6],
    coupon: {},
    suggestedProducts: [PRODUCTS_MOCK_DATA[4]],
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    price: { amount: "59.98", currency: "$" },
    discount: { amount: "12", currency: "%", type: "percentage" },
    shipping: { amount: "6.5", currency: "$" },
    finalPrice: { amount: "59.27", currency: "$" },
  },
  {
    id: "cart_8",
    products: PRODUCTS_MOCK_DATA,
    user: USERS_MOCK_DATA[0],
    coupon: {},
    suggestedProducts: [PRODUCTS_MOCK_DATA[6]],
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    price: { amount: "49.99", currency: "$" },
    discount: { amount: "0", currency: "$", type: "flat" },
    shipping: { amount: "5.99", currency: "$" },
    finalPrice: { amount: "55.98", currency: "$" },
  },
  {
    id: "cart_9",
    products: [PRODUCTS_MOCK_DATA[0], PRODUCTS_MOCK_DATA[1]],
    user: USERS_MOCK_DATA[1],
    coupon: {},
    suggestedProducts: [],
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    price: { amount: "69.99", currency: "$" },
    discount: { amount: "10", currency: "%", type: "percentage" },
    shipping: { amount: "8.99", currency: "$" },
    finalPrice: { amount: "71.99", currency: "$" },
  },
];

export const REVIEWS_MOCK_DATA = [
  {
    id: "rev_1",
    user: USERS_MOCK_DATA[0],
    title: "Great product!",
    text: "I really enjoyed using this, highly recommended.",
    rate: 4.8,
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    replies: [
      {
        id: "reply_1",
        user: USERS_MOCK_DATA[1],
        text: "Thank you for your feedback!",
        createdAt: "2025-09-01",
      },
    ],
    status: "accepted",
    entity: "product",
    media: [
      {
        src: "https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
        title: "Fern",
      },
      {
        src: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f",
        title: "Snacks",
      },
      {
        src: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25",
        title: "Mushrooms",
      },
    ],
    rejectionReason: "",
    isReply: false,
    likes: 3,
    dislikes: 0,
  },
  {
    id: "rev_2",
    user: USERS_MOCK_DATA[2],
    title: "Not what I expected",
    text: "The product quality could be better.",
    rate: 2.7,
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    replies: [],
    status: "pending",
    entity: "product",
    media: [],
    rejectionReason: "",
    isReply: false,
    likes: 1,
    dislikes: 2,
  },
  {
    id: "rev_3",
    user: USERS_MOCK_DATA[3],
    title: "Excellent!",
    text: "Arrived quickly and works perfectly.",
    rate: 5.0,
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    replies: [
      {
        id: "reply_2",
        user: USERS_MOCK_DATA[4],
        text: "Glad you liked it!",
        createdAt: "2025-09-02",
      },
    ],
    status: "accepted",
    entity: "product",
    media: [
      {
        src: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f",
        title: "Snacks",
      },
    ],
    rejectionReason: "",
    isReply: false,
    likes: 5,
    dislikes: 0,
  },
  {
    id: "rev_4",
    user: USERS_MOCK_DATA[5],
    title: "Terrible experience",
    text: "Item was broken and customer service didn’t respond.",
    rate: 1.3,
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    replies: [],
    status: "rejected",
    entity: "product",
    media: [
      {
        src: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25",
        title: "Mushrooms",
      },
    ],
    rejectionReason: "Inappropriate language used in review.",
    isReply: false,
    likes: 0,
    dislikes: 4,
  },
  {
    id: "rev_5",
    user: USERS_MOCK_DATA[6],
    title: "Good value for money",
    text: "Satisfied with the purchase overall.",
    rate: 4.2,
    createdAt: "2023-03-10",
    updatedAt: "2023-03-11",
    replies: [],
    status: "accepted",
    entity: "product",
    media: [],
    rejectionReason: "",
    isReply: false,
    likes: 2,
    dislikes: 0,
  },
];

export const CAMPAIGNS_MOCK_DATA = [
  {
    id: "cmp_1",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
        title: "Fern",
      },
      {
        src: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
        title: "Moss",
      },
      {
        src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
        title: "Palm",
      },
    ],
    createdAt: "2025-08-10",
    updatedAt: "2025-09-11",
    expiry: "2025-09-15", // expired
    products: PRODUCTS_MOCK_DATA,
    name: "Summer Clearance",
    excerpt: "End of season clearance sale.",
    description: `<p> Huge discounts on summer products. </p>`,
    startDate: "2025-08-01",
  },
  {
    id: "cmp_2",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
        title: "Watch",
      },
      {
        src: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
        title: "Shoes",
      },
    ],
    createdAt: "2025-09-01",
    updatedAt: "2025-09-10",
    expiry: "2025-12-01", // active
    products: PRODUCTS_MOCK_DATA,
    name: "Autumn Sale",
    excerpt: "Discounts on autumn essentials.",
    description: `<p> Cozy deals for the fall season. </p>`,
    startDate: "2025-09-15",
  },
  {
    id: "cmp_3",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
        title: "Winter Jacket",
      },
    ],
    createdAt: "2025-09-15",
    updatedAt: "2025-09-20",
    expiry: "2026-01-15", // upcoming
    products: PRODUCTS_MOCK_DATA,
    name: "Winter Specials",
    excerpt: "Prepare for the cold season.",
    description: `<p> Warm clothes at hot prices. </p>`,
    startDate: "2025-12-01",
  },
  {
    id: "cmp_4",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
        title: "Sneakers",
      },
    ],
    createdAt: "2025-09-12",
    updatedAt: "2025-09-18",
    expiry: "2025-09-30", // active but ending soon
    products: PRODUCTS_MOCK_DATA,
    name: "Back to School",
    excerpt: "Specials for students.",
    description: `<p> Perfect picks for the new semester. </p>`,
    startDate: "2025-09-01",
  },
  {
    id: "cmp_5",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1503602642458-232111445657",
        title: "Gift",
      },
    ],
    createdAt: "2025-09-05",
    updatedAt: "2025-09-06",
    expiry: "2025-10-20", // active
    products: PRODUCTS_MOCK_DATA,
    name: "Flash Deals",
    excerpt: "Limited-time offers.",
    description: `<p> Hurry! Deals end soon. </p>`,
    startDate: "2025-09-10",
  },
  {
    id: "cmp_6",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1473187983305-f615310e7daa",
        title: "Decor",
      },
    ],
    createdAt: "2025-09-08",
    updatedAt: "2025-09-12",
    expiry: "2026-03-01", // upcoming, long future
    products: PRODUCTS_MOCK_DATA,
    name: "Spring Festival",
    excerpt: "Celebrate with new arrivals.",
    description: `<p> Fresh looks for spring. </p>`,
    startDate: "2026-02-01",
  },
  {
    id: "cmp_7",
    banners: [
      {
        src: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
        title: "Food",
      },
    ],
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    expiry: "2025-09-22", // active
    products: PRODUCTS_MOCK_DATA,
    name: "Food Fiesta",
    excerpt: "Tasty deals on snacks.",
    description: `<p> Don’t miss out on limited food deals. </p>`,
    startDate: "2025-09-12",
  },
];

export const COUPONS_MOCK_DATA = [
  {
    id: "cpn_1",
    code: "WLCM-1000",
    type: "discount",
    users: [USERS_MOCK_DATA[0]],
    products: [PRODUCTS_MOCK_DATA[0]],
    cart: null,
    percentage: 15,
    amount: { amount: null, currency: "$" },
    expiry: "2026-01-25",
    usageNumber: 2,
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    used: 0,
  },
  {
    id: "cpn_2",
    code: "SPRING-25",
    type: "discount",
    users: [USERS_MOCK_DATA[1]],
    products: [PRODUCTS_MOCK_DATA[1]],
    cart: null,
    percentage: 25,
    amount: { amount: null, currency: "$" },
    expiry: "2026-05-01", // active
    usageNumber: 5,
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    used: 1,
  },
  {
    id: "cpn_3",
    code: "FREESHIP-50",
    type: "prize",
    users: [USERS_MOCK_DATA[2]],
    products: [],
    cart: null,
    percentage: null,
    amount: { amount: 50, currency: "$" },
    expiry: "2024-12-31", // expired
    usageNumber: 1,
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    used: 0,
  },
  {
    id: "cpn_4",
    code: "MEGA-100",
    type: "discount",
    users: [USERS_MOCK_DATA[3]],
    products: [PRODUCTS_MOCK_DATA[2]],
    cart: null,
    percentage: null,
    amount: { amount: 100, currency: "$" },
    expiry: "2025-09-15", // expired
    usageNumber: 3,
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    used: 3,
  },
  {
    id: "cpn_5",
    code: "LOYAL-10",
    type: "discount",
    users: [USERS_MOCK_DATA[4]],
    products: [],
    cart: null,
    percentage: 10,
    amount: { amount: null, currency: "$" },
    expiry: "2025-12-31", // active
    usageNumber: 10,
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    used: 5,
  },
  {
    id: "cpn_6",
    code: "NEWYEAR-500",
    type: "prize",
    users: [USERS_MOCK_DATA[5]],
    products: [PRODUCTS_MOCK_DATA[0], PRODUCTS_MOCK_DATA[2]],
    cart: null,
    percentage: null,
    amount: { amount: 500, currency: "$" },
    expiry: "2025-01-01", // expired
    usageNumber: 1,
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    used: 1,
  },
  {
    id: "cpn_7",
    code: "HALFOFF",
    type: "discount",
    users: [USERS_MOCK_DATA[6]],
    products: [],
    cart: null,
    percentage: 50,
    amount: { amount: null, currency: "$" },
    expiry: "2026-08-10", // active
    usageNumber: 4,
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    used: 2,
  },
  {
    id: "cpn_8",
    code: "WINTER-75",
    type: "prize",
    users: [USERS_MOCK_DATA[0], USERS_MOCK_DATA[3]],
    products: [PRODUCTS_MOCK_DATA[1]],
    cart: null,
    percentage: null,
    amount: { amount: 75, currency: "$" },
    expiry: "2025-10-01", // expired
    usageNumber: 2,
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    used: 2,
  },
  {
    id: "cpn_9",
    code: "VIP-30",
    type: "discount",
    users: [USERS_MOCK_DATA[2], USERS_MOCK_DATA[6]],
    products: [],
    cart: null,
    percentage: 30,
    amount: { amount: null, currency: "$" },
    expiry: "2026-03-15", // active
    usageNumber: 6,
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    used: 0,
  },
];

export const TRANSACTIONS_MOCK_DATA = [
  {
    id: "TRN_1",
    trackingCode: "KHSDG87682",
    referrerBank: "Bank of America",
    user: USERS_MOCK_DATA[0],
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    status: "successful",
    date: "2525-07-25",
    amount: "450$",
  },
  {
    id: "TRN_2",
    trackingCode: "JGHSI12345",
    referrerBank: "Chase Bank",
    user: USERS_MOCK_DATA[1],
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    status: "failed",
    date: "2525-07-24",
    amount: "320$",
  },
  {
    id: "TRN_3",
    trackingCode: "PLMKD67890",
    referrerBank: "Wells Fargo",
    user: USERS_MOCK_DATA[2],
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    status: "successful",
    date: "2525-07-23",
    amount: "150$",
  },
  {
    id: "TRN_4",
    trackingCode: "QWERT54321",
    referrerBank: "Citibank",
    user: USERS_MOCK_DATA[3],
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    status: "failed",
    date: "2525-07-22",
    amount: "700$",
  },
  {
    id: "TRN_5",
    trackingCode: "ZXCVB98765",
    referrerBank: "PNC Bank",
    user: USERS_MOCK_DATA[4],
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    status: "successful",
    date: "2525-07-21",
    amount: "120$",
  },
  {
    id: "TRN_6",
    trackingCode: "ASDFG11223",
    referrerBank: "HSBC",
    user: USERS_MOCK_DATA[5],
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    status: "failed",
    date: "2525-07-20",
    amount: "530$",
  },
  {
    id: "TRN_7",
    trackingCode: "QAZWS99887",
    referrerBank: "TD Bank",
    user: USERS_MOCK_DATA[6],
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    status: "successful",
    date: "2525-07-19",
    amount: "250$",
  },
];

export const CONTACT_FORMS_MOCK_DATA = [
  {
    id: "cntc_1",
    name: `${USERS_MOCK_DATA[0].firstName} ${USERS_MOCK_DATA[0].lastName}`,
    phone: "123-456-7890",
    email: USERS_MOCK_DATA[0].email,
    message: "I have a question about your services.",
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    response: "Thank you for reaching out! We'll get back to you soon.",
    status: "responded",
  },
  {
    id: "cntc_2",
    name: `${USERS_MOCK_DATA[1].firstName} ${USERS_MOCK_DATA[1].lastName}`,
    phone: "234-567-8901",
    email: USERS_MOCK_DATA[1].email,
    message: "Can you provide a quote for my project?",
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    response: "",
    status: "new",
  },
  {
    id: "cntc_3",
    name: `${USERS_MOCK_DATA[2].firstName} ${USERS_MOCK_DATA[2].lastName}`,
    phone: "345-678-9012",
    email: USERS_MOCK_DATA[2].email,
    message: "I want to know more about your pricing plans.",
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    response: "Pricing details have been sent to your email.",
    status: "responded",
  },
  {
    id: "cntc_4",
    name: `${USERS_MOCK_DATA[3].firstName} ${USERS_MOCK_DATA[3].lastName}`,
    phone: "456-789-0123",
    email: USERS_MOCK_DATA[3].email,
    message: "Is there a discount for long-term clients?",
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    response: "",
    status: "new",
  },
  {
    id: "cntc_5",
    name: `${USERS_MOCK_DATA[4].firstName} ${USERS_MOCK_DATA[4].lastName}`,
    phone: "567-890-1234",
    email: USERS_MOCK_DATA[4].email,
    message: "Can I schedule a meeting to discuss requirements?",
    response: "Meeting scheduled for next Monday at 10 AM.",
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    status: "responded",
  },
  {
    id: "cntc_6",
    name: `${USERS_MOCK_DATA[5].firstName} ${USERS_MOCK_DATA[5].lastName}`,
    phone: "678-901-2345",
    email: USERS_MOCK_DATA[5].email,
    message: "Do you provide support after project delivery?",
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    response: "",
    status: "new",
  },
  {
    id: "cntc_7",
    name: `${USERS_MOCK_DATA[6].firstName} ${USERS_MOCK_DATA[6].lastName}`,
    phone: "789-012-3456",
    email: USERS_MOCK_DATA[6].email,
    message: "I am interested in a custom solution.",
    response: "We will prepare a proposal and send it to you shortly.",
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    status: "responded",
  },
];

export const BLOG_MOCK_DATA = [
  {
    id: "blog_1",
    title: "The Future of AI in Everyday Life",
    excerpt:
      "Explore how AI is transforming the way we live, work, and communicate.",
    author: "Amir Atabak Ronaghinia",
    image: {
      src: "https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
      title: "AI Illustration",
    },
    timeToRead: "6 min",
    slug: "future-of-ai-everyday-life",
    reviews: [],
    tags: [],
    categories: [],
    suggestedProducts: [],
    relatedBlogs: [],
    isPublished: true,
    isFeatured: true,
    likes: 67,
    dislikes: 0,
    createdAt: "2025-09-11",
    updatedAt: "2025-09-13",
    text: `
      <p>Artificial Intelligence (AI) is no longer a concept of the future. It is already part of our daily lives, from smart assistants to recommendation systems and autonomous vehicles.</p>
      <p>As AI continues to evolve, it brings both opportunities and challenges. Companies are leveraging AI for efficiency and personalization, while society debates ethics, privacy, and job displacement.</p>
      <h2>How AI is Changing Daily Life</h2>
      <ul>
        <li><strong>Smart Homes:</strong> AI enables automated lighting, climate control, and security systems.</li>
        <li><strong>Healthcare:</strong> AI assists in diagnosis, personalized treatment plans, and patient monitoring.</li>
        <li><strong>Transportation:</strong> Self-driving cars and traffic optimization systems improve safety and reduce congestion.</li>
      </ul>
      <p>The integration of AI into daily routines promises a more convenient and connected world, but it also requires careful consideration of ethical implications.</p>
    `,
  },
  {
    id: "blog_2",
    title: "Sustainable Living: Tips for a Greener Lifestyle",
    excerpt:
      "Learn practical ways to reduce your environmental footprint and live more sustainably.",
    author: "Sara Kazemi",
    timeToRead: "5 min",
    slug: "sustainable-living-tips",
    reviews: [],
    
    categories: [],
    tags: [],
    suggestedProducts: [],
    relatedBlogs: [],
    isPublished: true,
    isFeatured: false,
    image: {
      src: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
      title: "Sustainable Living",
    },

    likes: 45,
    dislikes: 2,
    createdAt: "2025-09-12",
    updatedAt: "2025-09-14",
    text: `
      <p>Living sustainably doesn't have to be difficult. Small changes in your daily routine can have a significant impact on the environment.</p>
      <h2>Practical Tips for a Greener Lifestyle</h2>
      <ol>
        <li><strong>Reduce Waste:</strong> Recycle, compost, and avoid single-use plastics whenever possible.</li>
        <li><strong>Energy Efficiency:</strong> Use LED bulbs, unplug devices when not in use, and consider renewable energy sources.</li>
        <li><strong>Mindful Consumption:</strong> Buy locally produced goods and choose quality over quantity.</li>
        <li><strong>Transport:</strong> Walk, bike, or use public transportation to reduce your carbon footprint.</li>
      </ol>
      <p>Adopting sustainable habits benefits both the planet and your own wellbeing, creating a cleaner, healthier environment for everyone.</p>
    `,
  },
];
